In [1]:
import pandas as pd
import numpy as np
import seaborn as sb
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from pandas.plotting import scatter_matrix

In [2]:
columns_list = ['Year', 'YearHalf', 'Area', 'StateName', 'StateAb', 'DrivAge', 'Gender', 'VehCat', 'VehGroup', 'VehModel', 'VehYear', 'ExposTotal', 'PremTotal', 'ExposFireRob', 'PremFireRob', 'SumInsAvg', 'ClaimNbRob', 'ClaimAmountRob', 'ClaimNbPartColl', 'ClaimAmountPartColl', 'ClaimNbTotColl', 'ClaimAmountTotColl', 'ClaimNbFire', 'ClaimAmountFire', 'ClaimNbOther', 'ClaimAmountOther', 'ENVIO']

In [3]:
arq_casco_comp = pd.read_csv('data/arq_casco_comp.csv', sep=';')
auto_cat = pd.read_csv('data/auto_cat.csv', sep=';')
auto_idade = pd.read_csv('data/auto_idade.csv', sep=';')
auto_reg = pd.read_csv('data/auto_reg.csv', sep=';')
auto_sexo = pd.read_csv('data/auto_sexo.csv', sep=';')
auto2_vei = pd.read_csv('data/auto2_vei.csv', sep=';')
states = pd.read_csv('data/states.csv', sep=';')

In [4]:
arq_casco_comp.describe()

,VehCatCode,AreaCode,VehYear,DrivAgeCode,ExposFireRob,PremFireRob,ClaimNbRob,ClaimAmountRob,ClaimNbPartColl,ClaimAmountPartColl,ClaimNbTotColl,ClaimAmountTotColl,ClaimNbFire,ClaimAmountFire,ClaimNbOther,ClaimAmountOther
count,3.210981e+06,3.210981e+06,3.210981e+06,3.210981e+06,3210981.0,3210981.0,3.210981e+06,3.210981e+06,3.210981e+06,3.210981e+06,3.210981e+06,3.210981e+06,3.210981e+06,3.210981e+06,3.210981e+06,3.210981e+06
mean,2.227705e+00,1.696920e+01,2.012816e+03,2.839053e+00,0.0,0.0,1.773259e-02,6.526559e+02,1.563130e-01,9.976779e+02,1.874536e-02,8.258727e+02,7.605152e-04,2.728206e+01,6.044461e-01,3.618139e+02
std,1.730883e+00,1.310389e+01,6.013381e+00,1.706216e+00,0.0,0.0,2.296290e-01,9.672805e+03,2.155237e+00,1.838267e+04,1.506812e-01,8.551388e+03,3.124213e-02,1.674104e+03,3.353909e+00,3.514472e+03
min,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.000000e+00,8.000000e+00,2.010000e+03,2.000000e+00,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,1.000000e+00,1.400000e+01,2.014000e+03,3.000000e+00,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,3.000000e+00,2.300000e+01,2.017000e+03,4.000000e+00,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,9.000000e+00,9.900000e+01,2.021000e+03,5.000000e+00,0.0,0.0,1.600000e+02,7.669419e+06,2.615000e+03,3.091209e+07,3.900000e+01,1.506927e+06,1.900000e+01,6.203120e+05,3.810000e+02,1.961010e+06

In [5]:
arq_casco_comp['AreaCode'] = arq_casco_comp['AreaCode'].astype(str)
auto_reg['AreaCode'] = auto_reg['AreaCode'].astype(str)

In [6]:
tables = [ arq_casco_comp, auto_cat, auto_idade, auto_reg, auto_sexo, auto2_vei, states]
on_list = [['VehCatCode'], ['DrivAgeCode'], ['AreaCode'], ['GenderCode'], ['VehModelCode'], ['StateAb']]
merged = tables[0]
for tableIndex, table in enumerate(tables[1:]):
    print(f"Merging {on_list[tableIndex]}")
    merged = merged.merge(
        table,
        how='left',
        on=on_list[tableIndex]
    )

Merging ['VehCatCode']
Merging ['DrivAgeCode']
Merging ['AreaCode']
Merging ['GenderCode']
Merging ['VehModelCode']
Merging ['StateAb']

In [7]:
print(merged.shape)
print(arq_casco_comp.shape)

(3210981, 31)
(3210981, 22)

In [8]:
merged.describe()

,VehCatCode,VehYear,DrivAgeCode,ExposFireRob,PremFireRob,ClaimNbRob,ClaimAmountRob,ClaimNbPartColl,ClaimAmountPartColl,ClaimNbTotColl,ClaimAmountTotColl,ClaimNbFire,ClaimAmountFire,ClaimNbOther,ClaimAmountOther,VehGroupCode
count,3.210981e+06,3.210981e+06,3.210981e+06,3210981.0,3210981.0,3.210981e+06,3.210981e+06,3.210981e+06,3.210981e+06,3.210981e+06,3.210981e+06,3.210981e+06,3.210981e+06,3.210981e+06,3.210981e+06,3.170800e+06
mean,2.227705e+00,2.012816e+03,2.839053e+00,0.0,0.0,1.773259e-02,6.526559e+02,1.563130e-01,9.976779e+02,1.874536e-02,8.258727e+02,7.605152e-04,2.728206e+01,6.044461e-01,3.618139e+02,3.188243e+02
std,1.730883e+00,6.013381e+00,1.706216e+00,0.0,0.0,2.296290e-01,9.672805e+03,2.155237e+00,1.838267e+04,1.506812e-01,8.551388e+03,3.124213e-02,1.674104e+03,3.353909e+00,3.514472e+03,1.594302e+02
min,1.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
25%,1.000000e+00,2.010000e+03,2.000000e+00,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.680000e+02
50%,1.000000e+00,2.014000e+03,3.000000e+00,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.260000e+02
75%,3.000000e+00,2.017000e+03,4.000000e+00,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.720000e+02
max,9.000000e+00,2.021000e+03,5.000000e+00,0.0,0.0,1.600000e+02,7.669419e+06,2.615000e+03,3.091209e+07,3.900000e+01,1.506927e+06,1.900000e+01,6.203120e+05,3.810000e+02,1.961010e+06,5.620000e+02

In [9]:
merged['Year'] = '2019'
merged['YearHalf'] = '2nd'
merged = merged[columns_list]

In [10]:
merged.columns

Index(['Year', 'YearHalf', 'Area', 'StateName', 'StateAb', 'DrivAge', 'Gender',
       'VehCat', 'VehGroup', 'VehModel', 'VehYear', 'ExposTotal', 'PremTotal',
       'ExposFireRob', 'PremFireRob', 'SumInsAvg', 'ClaimNbRob',
       'ClaimAmountRob', 'ClaimNbPartColl', 'ClaimAmountPartColl',
       'ClaimNbTotColl', 'ClaimAmountTotColl', 'ClaimNbFire',
       'ClaimAmountFire', 'ClaimNbOther', 'ClaimAmountOther', 'ENVIO'],
      dtype='object')

In [11]:
merged.describe()

,VehYear,ExposFireRob,PremFireRob,ClaimNbRob,ClaimAmountRob,ClaimNbPartColl,ClaimAmountPartColl,ClaimNbTotColl,ClaimAmountTotColl,ClaimNbFire,ClaimAmountFire,ClaimNbOther,ClaimAmountOther
count,3.210981e+06,3210981.0,3210981.0,3.210981e+06,3.210981e+06,3.210981e+06,3.210981e+06,3.210981e+06,3.210981e+06,3.210981e+06,3.210981e+06,3.210981e+06,3.210981e+06
mean,2.012816e+03,0.0,0.0,1.773259e-02,6.526559e+02,1.563130e-01,9.976779e+02,1.874536e-02,8.258727e+02,7.605152e-04,2.728206e+01,6.044461e-01,3.618139e+02
std,6.013381e+00,0.0,0.0,2.296290e-01,9.672805e+03,2.155237e+00,1.838267e+04,1.506812e-01,8.551388e+03,3.124213e-02,1.674104e+03,3.353909e+00,3.514472e+03
min,0.000000e+00,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.010000e+03,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2.014000e+03,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,2.017000e+03,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,2.021000e+03,0.0,0.0,1.600000e+02,7.669419e+06,2.615000e+03,3.091209e+07,3.900000e+01,1.506927e+06,1.900000e+01,6.203120e+05,3.810000e+02,1.961010e+06

In [12]:
# ExposFireRob, PremFireRob contain 0s 
drop_list = ['ExposFireRob', 'PremFireRob']

In [13]:
merged = merged.drop(columns=drop_list)

In [14]:
merged.to_csv('data/merged.csv', sep=';')

In [17]:
print('\n'.join([f'Column {column}, unique - {len(merged[column].unique())}' for column in merged.columns]))

['Column Year, unique - 1', 'Column YearHalf, unique - 1', 'Column Area, unique - 41', 'Column StateName, unique - 28', 'Column StateAb, unique - 28', 'Column DrivAge, unique - 6', 'Column Gender, unique - 4', 'Column VehCat, unique - 8', 'Column VehGroup, unique - 504', 'Column VehModel, unique - 7569', 'Column VehYear, unique - 74', 'Column ExposTotal, unique - 434610', 'Column PremTotal, unique - 2370287', 'Column SumInsAvg, unique - 2557350', 'Column ClaimNbRob, unique - 41', 'Column ClaimAmountRob, unique - 31376', 'Column ClaimNbPartColl, unique - 102', 'Column ClaimAmountPartColl, unique - 43533', 'Column ClaimNbTotColl, unique - 11', 'Column ClaimAmountTotColl, unique - 36376', 'Column ClaimNbFire, unique - 5', 'Column ClaimAmountFire, unique - 2126', 'Column ClaimNbOther, unique - 238', 'Column ClaimAmountOther, unique - 24679', 'Column ENVIO, unique - 1']